### ISSUE TITLE
Assignment 3 code snippet ppf misprint

### ISSUE THREAD

**Issue by damides** [lucabaldini/cmepda#8]
I think that the way the ppf is plotted is wrong. 
Line 53 `plt.plot(x, pdf.ppf(x))` should be something like:
`plt.plot(pdf.ycdf, pdf.ppf(pdf.ycdf))` (+ ycdf must be defined as self.ycdf in class declaration)

As far as I understand the pdf spline is computed when the class is instantiated (so with the original x np.array). When it's called for plotting its array argument is used to compute the 'y' values of the spline so it doesn't make sense to compute values very far to the interval where the pdf lays. 
I attach two picture below: the first one is the output of the snippet, the second one is the output of the proposed correction. 

I thought it was worth pointing it out, even if I'm wrong I'll use this issue to understand better the matter regarding the call to the pdf method. 

![ppf1](https://user-images.githubusercontent.com/37851418/66962083-6f8c9b80-f070-11e9-921c-5eebe680458d.png)
![ppf_2](https://user-images.githubusercontent.com/37851418/66962082-6ef40500-f070-11e9-9587-7b9626047ef9.png)

**Comment by lucabaldini** [comment]
You are 100% correct---my apologies for overlooking this.

(The example that we wrote in the classroom only worked because the support of the original pdf happened to be [0, 1]).

I'd recommend not using pdf.ycdf, bu t defining a new grid between 0 and 1, as this makes clear that the ppf is a spline and can be evaluated in any point---not just those used for its definition. Also, the labels should read "q" and "ppf(q)".

Here is a proposed edit:
https://github.com/lucabaldini/cmepda/commit/74fbef3d4ac91fd549dbd80622e60b9453bc2527
